stages:

  preprocess:
    cmd: python src/preprocessing.py
    deps:
      - data/raw/diabetes.csv
      - src/preprocessing.py
    outs:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv

  train:
    cmd: python src/train.py
    deps:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv
      - src/train.py
    outs:
      - models/diabetes_model.pkl